name: IntelliJ Plugin Verifier
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [master]
    paths: [ 'intellij-plugin-verifier/**', '.github/workflows/intellij-plugin-verifier.yml' ]
  # Trigger the workflow on any pull request
  pull_request:
    paths: [ 'intellij-plugin-verifier/**', '.github/workflows/intellij-plugin-verifier.yml' ]

jobs:

  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v6.0.2

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v5.0.2

  # Run tests
  test:
    name: Test
    needs: gradleValidation
    runs-on: ubuntu-latest
    steps:

      # Setup Java 17 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v6.0.2

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v5.0.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v5.0.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Publish dev lib versions
      - name: Publish Dev Version
        run: |
          cd plugins-verifier-service
          ./gradlew :intellij-plugin-structure:publishToMavenLocal

      # Run tests
      - name: Run Tests
        run: |
          cd intellij-plugin-verifier
          ./gradlew test

      - name: Collect Test Results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: test-results-intellij-plugin-verifier
          path: ${{ github.workspace }}/intellij-plugin-verifier/build/reports/problems/
